In [6]:
import numpy as np
import scipy.sparse as sp
np.random.seed(12)


import warnings
#Comment this to turn on warnings
warnings.filterwarnings('ignore')

### define Ising model aprams
# system size
L=40

# create 10000 random Ising states
states=np.random.choice([-1, 1], size=(10000,L))

def ising_energies(states,L):
    """
    This function calculates the energies of the states in the nn Ising Hamiltonian
    """
    J=np.zeros((L,L),)
    for i in range(L):
        J[i,(i+1)%L]-=1.0
    # compute energies
    E = np.einsum('...i,ij,...j->...',states,J,states)

    return E
# calculate Ising energies
energies=ising_energies(states,L)
print(states)
print(states.shape)
print(energies.shape)

[[ 1  1 -1 ... -1 -1 -1]
 [-1 -1  1 ... -1 -1 -1]
 [-1  1  1 ... -1 -1  1]
 ...
 [-1  1 -1 ... -1 -1  1]
 [ 1 -1 -1 ...  1 -1  1]
 [-1 -1  1 ... -1  1 -1]]
(10000, 40)
(10000,)


In [8]:
# reshape Ising states into RL samples: S_iS_j --> X_p
states=np.einsum('...i,...j->...ij', states, states)
shape=states.shape
states=states.reshape((shape[0],shape[1]*shape[2]))
# build final data set
Data=[states,energies]
print("done2")

MemoryError: 

In [10]:

np.logspace(-1,1,2)





array([ 0.1, 10. ])

In [22]:
# a) producing data for Ising model
import numpy as np
import scipy.sparse as sp
np.random.seed(12)

import warnings
warnings.filterwarnings('ignore')

### define Ising model aprams
# system size
L=40
# create n_sample = 10000 random Ising states
n_sample=10000
states_ori=np.random.choice([-1,1], size=(n_sample,L))

# define functions

def ising_energies(states,L):
    """
    This function calculates the energies of the states in the nn Ising Hamiltonian
    """
    J=np.zeros((L,L),)
    for i in range(L):
        J[i,(i+1)%L]-=1.0
    
    # compute energies
    E = np.einsum('...i,ij,...j->...',states,J,states)
    
    return E

# calculate Ising energies
energies=ising_energies(states_ori,L)
print("done producing Ising data")
print("----------------congratuations----------------")


done producing Ising data
----------------congratuations----------------


In [92]:
# import necessary packages
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split

# sigmoid function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

# 
def feed_forward(X):
    # weighted sum of inputs to the hidden layer
    z_h = np.matmul(X, hidden_weights) + hidden_bias
    # activation in the hidden layer
    a_h = sigmoid(z_h)
    
    # weighted sum of inputs to the output layer
    z_o = np.matmul(a_h, output_weights) + output_bias
    # softmax output
    # axis 0 holds each input and axis 1 the probabilities of each category
    exp_term = np.exp(z_o)
    probabilities = exp_term / np.sum(exp_term, axis=1, keepdims=True)
    
    return probabilities
def feed_forward_train(X):
    # weighted sum of inputs to the hidden layer
    z_h = np.matmul(X, hidden_weights) + hidden_bias
    # activation in the hidden layer
    a_h = sigmoid(z_h)
    
    # weighted sum of inputs to the output layer
    z_o = np.matmul(a_h, output_weights) + output_bias
    # softmax output
    # axis 0 holds each input and axis 1 the probabilities of each category
    exp_term = np.exp(z_o)
    probabilities = exp_term / np.sum(exp_term, axis=1, keepdims=True)
    
    # for backpropagation need activations in hidden and output layers
    return a_h, probabilities

def backpropagation(X, Y):
    a_h, probabilities = feed_forward_train(X)
    
    # error in the output layer
    error_output = probabilities - Y
    # error in the hidden layer
    error_hidden = np.matmul(error_output, output_weights.T) * a_h * (1 - a_h)
    
    # gradients for the output layer
    output_weights_gradient = np.matmul(a_h.T, error_output)
    output_bias_gradient = np.sum(error_output, axis=0)
    
    # gradient for the hidden layer
    hidden_weights_gradient = np.matmul(X.T, error_hidden)
    hidden_bias_gradient = np.sum(error_hidden, axis=0)

    return output_weights_gradient, output_bias_gradient, hidden_weights_gradient, hidden_bias_gradient

def to_categorical_numpy(integer_vector):    
    n_inputs = len(integer_vector)
    unique_values = np.array(list(set(integer_vector)))
    n_categories = len(unique_values)
    onehot_vector = np.zeros((n_inputs, n_categories))
    for iI in range(n_inputs):
        onehot_vector[iI, int(np.asarray(np.where(unique_values == integer_vector[iI])))] = 1
        
    return onehot_vector

# we obtain a prediction by taking the class with the highest likelihood
def predict(X):
    probabilities = feed_forward(X)
    return np.argmax(probabilities, axis=1)


# ensure the same random numbers appear every time
np.random.seed(0)
n_hidden_neurons = 50

states=np.einsum('...i,...j->...ij', states_ori, states_ori)
shape=states.shape
states=states.reshape((shape[0],shape[1]*shape[2]))
Y_onehot = to_categorical_numpy(energies)

X_train, X_test, Y_train_onehot, Y_test_onehot = train_test_split(states, Y_onehot, test_size=0.25)
n_inputs, n_features = X_train.shape

n_categories = Y_onehot.shape[1]

# weights and bias in the hidden layer
hidden_weights = np.random.randn(n_features, n_hidden_neurons)
hidden_bias = np.zeros(n_hidden_neurons) + 0.01

# weights and bias in the output layer
output_weights = np.random.randn(n_hidden_neurons, n_categories)
output_bias = np.zeros(n_categories) + 0.01

probabilities = feed_forward(X_train)
#print("probabilities = (n_inputs, n_categories) = " + str(probabilities.shape))
#print("probability that image 0 is in category 0,1,2,...,9 = \n" + str(probabilities[0]))
#print("probabilities sum up to: " + str(probabilities[0].sum()))
#print()


predictions = predict(X_train)

eta = 0.01
lmbd = 0.01
for i in range(1000):
    # calculate gradients
    dWo, dBo, dWh, dBh = backpropagation(X_train, Y_train_onehot)
    # regularization term gradients
    dWo += lmbd * output_weights
    dWh += lmbd * hidden_weights
    
    # update weights and biases
    output_weights -= eta * dWo
    output_bias -= eta * dBo
    hidden_weights -= eta * dWh
    hidden_bias -= eta * dBh



(10000, 11)
